### ISSUE TITLE
Checkpoint files

### ISSUE THREAD

**Issue by trangham283** [ihp-lab/mm_analysis_empathy#1]
Hi @yufengyin

It seems like the [checkpoint files](https://github.com/ihp-lab/mm_analysis_empathy?tab=readme-ov-file#checkpoints) have been moved -- I can't download them. Can you help look into this? 

Trang

**Comment by yufengyin** [comment]
Hi Trang,

USC limited the Google Drive data storge to 100GB and thus I removed most of my stuff on the drive. I am uploading the checkpoints back to the drive. Once done, I will let you know.

Yufeng

**Comment by yufengyin** [comment]
Hi Trang,

I have uploaded the checkpoints and updated the links in the readme file. Please take a look.

Yufeng

**Comment by trangham283** [comment]
Looks good now, thanks Yufeng!
